(async()=>{"use strict";
const game=Switcher.normalizeId(Switcher.qs("game",Switcher.app.defaultGame));
const debug=Switcher.qs("debug","")==="1";
const front=document.getElementById("program"), back=document.getElementById("programNext");
const replayVideo=document.getElementById("replayVideo"),diagnostic=document.getElementById("diagnostic"),overlay=document.getElementById("overlayFrame"),overlayViewport=document.getElementById("overlayViewport"),fade=document.getElementById("fade"),black=document.getElementById("black"),replayBug=document.getElementById("replayBug"),replayTransition=document.getElementById("replayTransition"),replayTransitionImage=document.getElementById("replayTransitionImage"),replayTransitionVideo=document.getElementById("replayTransitionVideo"),replayTransitionFallback=document.getElementById("replayTransitionFallback");
const client=sessionStorage.getItem("broadcast1300")||Switcher.randomId("broadcast");sessionStorage.setItem("broadcast1300",client);if(debug)document.documentElement.classList.add("debug");
let db,ice=[],active=null,pending=null,currentCam="",requestedCam="",retryTimer=null,retry=0,lastCommand="",recorder=null,segments=[],segmentTimer=null,replayPlaying=false,generation=0,switchToken=0,replayEnabled=false,replayTransitionConfig={sport:"baseball",url:"../assets/replay/baseball.svg",durationMs:1200,outro:true};
const status=t=>diagnostic.textContent=t;

function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function absoluteMediaUrl(url){try{return new URL(String(url||""),location.href).href}catch{return ""}}
async function showReplayTransition(config={}){const c={...replayTransitionConfig,...config},duration=Math.max(300,Math.min(5000,+c.durationMs||1200)),url=absoluteMediaUrl(c.url);replayTransitionImage.style.display="none";replayTransitionVideo.style.display="none";replayTransitionFallback.style.display="none";try{replayTransitionVideo.pause()}catch{}replayTransitionVideo.removeAttribute("src");replayTransitionImage.removeAttribute("src");const isVideo=/\.(mp4|webm|mov)(?:[?#]|$)/i.test(url);if(url&&isVideo){replayTransitionVideo.style.display="block";replayTransitionVideo.src=url;replayTransitionVideo.currentTime=0;replayTransitionVideo.muted=true;replayTransitionVideo.play().catch(()=>{})}else if(url){replayTransitionImage.style.display="block";replayTransitionImage.src=url+(url.includes("?")?"&":"?")+"replay="+Date.now()}else{replayTransitionFallback.style.display="block";replayTransitionFallback.innerHTML=`REPLAY<span>${String(c.sport||"DEPORTES").toUpperCase()}</span>`}replayTransition.classList.add("show");await sleep(duration);replayTransition.classList.remove("show");try{replayTransitionVideo.pause()}catch{}replayTransitionVideo.removeAttribute("src");replayTransitionImage.removeAttribute("src")}
function sendOverlayMedia(data){try{overlay.contentWindow?.postMessage({type:"switcher-overlay-media",payload:data||{}},"*")}catch{}}
function mime(){return["video/webm;codecs=vp8,opus","video/webm;codecs=vp8","video/webm"].find(t=>window.MediaRecorder&&MediaRecorder.isTypeSupported(t))||""}
async function replayStatus(extra={}){if(!db)return;const seconds=segments.reduce((n,x)=>n+x.seconds,0);await db.ref(`switcher/${game}/broadcast/replayStatus`).set({supported:!!window.MediaRecorder,ready:seconds>=4,bufferSeconds:Math.min(seconds,Switcher.app.replay.maxSeconds),playing:replayPlaying,updatedAt:firebase.database.ServerValue.TIMESTAMP,...extra})}
function stopBuffer(){generation++;clearTimeout(segmentTimer);try{if(recorder&&recorder.state!=="inactive")recorder.stop()}catch{}recorder=null;segments=[]}
function startBuffer(stream){stopBuffer();const track=stream.getVideoTracks()[0];if(!track||!window.MediaRecorder){replayStatus({supported:false,message:"Replay no disponible"});return}const gen=++generation,m=mime(),ms=Switcher.app.replay.segmentMs,max=Switcher.app.replay.maxSegments;const next=()=>{if(gen!==generation||!active||track.readyState!=="live")return;let chunks=[];try{recorder=new MediaRecorder(new MediaStream(stream.getTracks().filter(t=>t.readyState==="live")),{...(m?{mimeType:m}:{}),videoBitsPerSecond:Switcher.app.replay.videoBitsPerSecond})}catch(e){replayStatus({supported:false,message:e.message});return}recorder.ondataavailable=e=>e.data?.size&&chunks.push(e.data);recorder.onstop=()=>{if(gen!==generation)return;if(chunks.length){segments.push({blob:new Blob(chunks,{type:recorder.mimeType||m||"video/webm"}),seconds:ms/1000});while(segments.length>max)segments.shift();replayStatus({message:"Buffer grabando"})}setTimeout(next,0)};recorder.start(250);segmentTimer=setTimeout(()=>{try{recorder.state==="recording"&&recorder.stop()}catch{}},ms)};next()}
async function finishReplay(useTransition=true){if(useTransition&&replayTransitionConfig.outro)await showReplayTransition(replayTransitionConfig);fade.classList.add("show");setTimeout(()=>fade.classList.remove("show"),300);replayPlaying=false;try{replayVideo.pause()}catch{}replayVideo.classList.remove("show");replayBug.classList.remove("show");replayVideo.removeAttribute("src");replayVideo.load();await replayStatus({playing:false,message:"LIVE"})}
async function playReplay(start=0,end=10,speed=.5){if(replayPlaying||!segments.length)return;const available=Math.floor(segments.reduce((n,x)=>n+x.seconds,0)),segSec=Switcher.app.replay.segmentMs/1000;start=Math.max(0,Math.floor(+start||0));end=Math.min(available,Math.max(start+1,Math.floor(+end||10)));const startIndex=Math.floor(start/segSec),endIndex=Math.ceil(end/segSec),sel=segments.slice(startIndex,endIndex),total=sel.reduce((n,x)=>n+x.seconds,0);if(!sel.length)return replayStatus({playing:false,message:"Intervalo sin video disponible"});replayPlaying=true;await showReplayTransition(replayTransitionConfig);replayVideo.playbackRate=Math.max(.1,Math.min(1,+speed||1));replayVideo.muted=(+speed||1)<1;replayVideo.classList.add("show");replayBug.classList.add("show");fade.classList.add("show");setTimeout(()=>fade.classList.remove("show"),300);await replayStatus({playing:true,message:`Intervalo ${start}s → ${end}s · ${total}s · ×${speed}`});let playIndex=0;const next=async()=>{if(!replayPlaying)return;if(playIndex>=sel.length)return finishReplay();const url=URL.createObjectURL(sel[playIndex++].blob);replayVideo.src=url;replayVideo.onended=()=>{URL.revokeObjectURL(url);next()};replayVideo.onerror=()=>{URL.revokeObjectURL(url);next()};try{await replayVideo.play()}catch{URL.revokeObjectURL(url);finishReplay()}};next()}
async function destroy(s,remove=true){if(!s)return;try{s.answer?.off();s.candidates?.off();clearInterval(s.stats);s.pc?.close();s.video.pause();s.video.srcObject=null}catch{}if(remove&&db&&s.base)await Switcher.safeRemove(db.ref(s.base))}
function schedule(msg){clearTimeout(retryTimer);retry++;const d=Math.min(1000*Math.pow(1.5,retry-1),8000);status(`V14 · ${msg} · reintento ${Math.round(d/1000)}s`);retryTimer=setTimeout(()=>requestSwitch(requestedCam),d)}
async function promote(s,token){if(token!==switchToken||pending!==s)return;const old=active;active=s;pending=null;currentCam=s.cam;s.video.classList.add("live");if(old&&old.video!==s.video)old.video.classList.remove("live");status(`V14 · ${s.cam.toUpperCase()} · VIDEO AL AIRE`);if(replayEnabled)startBuffer(s.stream);else replayStatus({ready:false,message:"Modo frío · buffer apagado"});setTimeout(()=>destroy(old),260)}
async function buildSession(cam,videoEl,token){const id=`broadcast-${client}-${cam}-${Date.now().toString(36)}`,base=`switcher/${game}/cameraSignaling/${cam}/${id}`,pc=new RTCPeerConnection(Switcher.peerConfig(ice)),q=Switcher.makeIceQueue(pc),stream=new MediaStream();const s={cam,pc,base,stream,video:videoEl,answer:null,candidates:null,stats:null,hasFrames:false};videoEl.srcObject=stream;videoEl.muted=false;videoEl.volume=1;pc.addTransceiver("video",{direction:"recvonly"});pc.addTransceiver("audio",{direction:"recvonly"});pc.ontrack=e=>{if(!stream.getTracks().some(t=>t.id===e.track.id))stream.addTrack(e.track);videoEl.play().catch(()=>{});if(e.track.kind==="video")status(`V14 · ${cam.toUpperCase()} · pista recibida · preparando cambio`)};let ready=false,pendingIce=[];pc.onicecandidate=e=>{if(!e.candidate)return;const x=e.candidate.toJSON();ready?db.ref(`${base}/viewerCandidates`).push(x):pendingIce.push(x)};pc.onconnectionstatechange=()=>{if(token!==switchToken)return;if(pc.connectionState==="failed")schedule("recuperando señal");else if(!s.hasFrames)status(`V14 · ${cam.toUpperCase()} · ${pc.connectionState} · esperando imagen`)};const candidates=db.ref(`${base}/cameraCandidates`),answer=db.ref(`${base}/answer`);candidates.on("child_added",snap=>snap.val()&&q.add(snap.val()));answer.on("value",async snap=>{if(snap.val()&&!pc.currentRemoteDescription){try{await pc.setRemoteDescription(snap.val());await q.flush()}catch(e){schedule(e.message)}}});s.answer=answer;s.candidates=candidates;await pc.setLocalDescription(await pc.createOffer());await db.ref(base).set({role:"broadcast-direct",clientId:client,createdAt:firebase.database.ServerValue.TIMESTAMP,offer:{type:pc.localDescription.type,sdp:pc.localDescription.sdp}});ready=true;for(const x of pendingIce)await db.ref(`${base}/viewerCandidates`).push(x);let lastFrames=0;s.stats=setInterval(async()=>{if(token!==switchToken||pending!==s)return;try{let r;(await pc.getStats()).forEach(x=>{if(x.type==="inbound-rtp"&&x.kind==="video"&&!x.isRemote)r=x});if(!r)return;const f=r.framesDecoded||0,b=r.bytesReceived||0;if(f>lastFrames&&videoEl.videoWidth>0&&videoEl.readyState>=2){s.hasFrames=true;retry=0;await promote(s,token)}else status(`V14 · ${cam.toUpperCase()} · preparando imagen (${b} bytes)`);lastFrames=f}catch{}},500);return s}
async function requestSwitch(cam){clearTimeout(retryTimer);requestedCam=cam||"";const token=++switchToken;if(pending){await destroy(pending);pending=null}if(!cam){status("V14 · espera una cámara en PROGRAM");return}if(active?.cam===cam&&active.pc.connectionState==="connected"){status(`V14 · ${cam.toUpperCase()} · VIDEO AL AIRE`);return}const target=active?.video===front?back:front;target.classList.remove("live");target.style.background="#000";status(`V14 · preparando ${cam.toUpperCase()} sin cortar la señal actual`);try{pending=await buildSession(cam,target,token)}catch(e){if(token===switchToken)schedule(e.message)}}
document.addEventListener("click",()=>{for(const v of [front,back,replayVideo]){v.muted=false;v.volume=1;v.play().catch(()=>{})}},{passive:true});
try{db=Switcher.initFirebase();ice=await Switcher.getIceServers({game,role:"broadcast",clientId:client});db.ref(`switcher/${game}/program`).on("value",s=>{const cam=s.val()||"";if(cam!==requestedCam)requestSwitch(cam)});db.ref(`switcher/${game}/transition`).on("value",s=>{const v=s.val();if(!v)return;fade.style.transitionDuration=`${v.duration||450}ms`;fade.classList.add("show");setTimeout(()=>fade.classList.remove("show"),(v.duration||450)+80)});db.ref(`switcher/${game}/black`).on("value",s=>black.classList.toggle("show",!!s.val()));db.ref(`switcher/${game}/broadcast/overlay`).on("value",s=>{const v=s.val()||{};let url=(v.url||Switcher.app.defaultOverlayUrl||"").trim();const legacy=/beisbol-overlay\.web\.app\/overlay\.html/i.test(url);if(!url||legacy)url=new URL("../overlay/index.html?embedded=1",location.href).href;else url=new URL(url,location.href).href;overlayViewport.style.display=v.enabled===false?"none":"block";if(overlay.src!==url)overlay.src=url});db.ref(`switcher/${game}/broadcast/replayEnabled`).on("value",s=>{replayEnabled=!!s.val();if(replayEnabled&&active?.stream)startBuffer(active.stream);else if(!replayEnabled){stopBuffer();replayStatus({ready:false,bufferSeconds:0,message:"Modo frío · buffer apagado"})}});db.ref(`switcher/${game}/broadcast/replayCommand`).on("value",s=>{const c=s.val();if(!c?.id||c.id===lastCommand)return;lastCommand=c.id;c.action==="play"?playReplay(Number.isFinite(+c.start)?+c.start:0,Number.isFinite(+c.end)?+c.end:(+c.seconds||10),+c.speed||.5):c.action==="testTransition"?showReplayTransition(replayTransitionConfig):finishReplay(false)});db.ref(`switcher/${game}/broadcast/replayTransition`).on("value",s=>{replayTransitionConfig={...replayTransitionConfig,...(s.val()||{})}});db.ref(`switcher/${game}/broadcast/mediaCommand`).on("value",s=>{const v=s.val();if(v?.id)sendOverlayMedia(v)});overlay.addEventListener("load",async()=>{try{const snap=await db.ref(`switcher/${game}/broadcast/mediaCommand`).once("value");if(snap.val())sendOverlayMedia(snap.val())}catch{}});window.addEventListener("online",()=>requestSwitch(requestedCam));status("V14 · listo · esperando PROGRAM")}catch(e){status(`V14 · ERROR: ${e.message}`)}})();
