(async()=>{"use strict";
const $=id=>document.getElementById(id);
const game=Switcher.normalizeId(Switcher.qs("game",Switcher.app.defaultGame));
const cams=Switcher.app.cameras||["cam1","cam2","cam3"];
const client=sessionStorage.getItem("director1100")||Switcher.randomId("director");sessionStorage.setItem("director1100",client);
$("session").textContent=`Partido: ${game} · V11.0.0`;
let db,ice=[],program="",preview="",isBlack=false;const peers=new Map(),online=new Set();
const log=m=>$("log").textContent=`${new Date().toLocaleTimeString()} ${m}\n`+$("log").textContent.slice(0,6000);

// ===== V11 REPLAY ASISTIDO: PREVIEW LOCAL + ENVIAR AL AIRE =====
let previewRecorder=null,previewSegments=[],previewGen=0,previewTimer=null,previewUrl=null,previewPlaying=false,previewQueue=[],previewIndex=0;
function replayMime(){return ["video/webm;codecs=vp8,opus","video/webm;codecs=vp8","video/webm"].find(t=>window.MediaRecorder&&MediaRecorder.isTypeSupported(t))||""}
function stopPreviewBuffer(){previewGen++;clearTimeout(previewTimer);try{if(previewRecorder&&previewRecorder.state!=="inactive")previewRecorder.stop()}catch{}previewRecorder=null;previewSegments=[];updateLocalReplayStatus()}
function updateLocalReplayStatus(){const sec=previewSegments.reduce((n,x)=>n+x.seconds,0);const el=$("localReplayReady");if(el){el.textContent=sec>=4?`PREVIEW BUFFER ${Math.floor(sec)}s`:"PREVIEW CARGANDO";el.className=`badge ${sec>=4?"good":"warn"}`}}
function startPreviewBuffer(){stopPreviewBuffer();const v=program?$("video-"+program):null,stream=v?.srcObject;if(!stream||!window.MediaRecorder)return;const track=stream.getVideoTracks()[0];if(!track||track.readyState!=="live")return setTimeout(startPreviewBuffer,1000);const gen=++previewGen,ms=Switcher.app.replay.segmentMs||2000,max=Switcher.app.replay.maxSegments||15,m=replayMime();const next=()=>{if(gen!==previewGen||track.readyState!=="live")return;let chunks=[];try{previewRecorder=new MediaRecorder(new MediaStream(stream.getTracks().filter(t=>t.readyState==="live")),{...(m?{mimeType:m}:{}),videoBitsPerSecond:900000})}catch(e){log("Replay preview: "+e.message);return}previewRecorder.ondataavailable=e=>e.data?.size&&chunks.push(e.data);previewRecorder.onstop=()=>{if(gen!==previewGen)return;if(chunks.length){previewSegments.push({blob:new Blob(chunks,{type:previewRecorder.mimeType||m||"video/webm"}),seconds:ms/1000});while(previewSegments.length>max)previewSegments.shift();updateLocalReplayStatus()}setTimeout(next,0)};previewRecorder.start(250);previewTimer=setTimeout(()=>{try{previewRecorder.state==="recording"&&previewRecorder.stop()}catch{}},ms)};next()}
function selectedReplaySegments(){const seconds=+$('replaySeconds').value||10,delay=+$('replayDelay').value||0,segSec=(Switcher.app.replay.segmentMs||2000)/1000;let i=Math.max(0,previewSegments.length-1-Math.ceil(delay/segSec)),sel=[],total=0;for(;i>=0&&total<seconds;i--){sel.unshift(previewSegments[i]);total+=previewSegments[i].seconds}return sel}
async function closeReplayPreview(){previewPlaying=false;const box=$("replayPreviewModal"),v=$("replayPreviewVideo");try{v.pause()}catch{}if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null}previewQueue=[];previewIndex=0;v.onended=null;v.onerror=null;v.removeAttribute("src");v.load();box.classList.remove("show")}
async function previewReplay(){const sel=selectedReplaySegments();if(!sel.length)return alert("Espera a que el buffer de PREVIEW tenga al menos 4 segundos");await closeReplayPreview();const v=$("replayPreviewVideo"),box=$("replayPreviewModal"),speed=+$('replaySpeed').value||.5;previewQueue=sel;previewIndex=0;box.classList.add("show");previewPlaying=true;const next=async()=>{if(!previewPlaying||previewIndex>=previewQueue.length)return; if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(previewQueue[previewIndex++].blob);v.src=previewUrl;v.playbackRate=speed;v.muted=speed<1;v.onended=next;v.onerror=next;try{await v.play()}catch(e){log("Preview replay: "+e.message);next()}};next()}
async function sendReplayToAir(){const sec=+$('replaySeconds').value||10,speed=+$('replaySpeed').value||.5,delay=+$('replayDelay').value||0;await closeReplayPreview();await db.ref(`switcher/${game}/broadcast/replayCommand`).set({id:Date.now()+"-play",action:"play",seconds:sec,speed,delay,source:"program",at:Date.now()});}

function render(){const g=$("cameraGrid");g.innerHTML="";cams.forEach(c=>{const a=document.createElement("article");a.className="panel";a.innerHTML=`<div class="video-card" id="card-${c}"><video id="video-${c}" autoplay playsinline muted></video><div class="overlay-top"><span id="presence-${c}" class="badge warn">Sin señal</span><span id="state-${c}" class="badge">offline</span></div></div><div class="kpis"><div class="kpi"><b id="bitrate-${c}">0 kbps</b><span>Bitrate</span></div><div class="kpi"><b id="rtt-${c}">—</b><span>RTT</span></div><div class="kpi"><b id="fps-${c}">0</b><span>FPS</span></div><div class="kpi"><b id="res-${c}">—</b><span>Resolución</span></div><div class="kpi"><b id="bat-${c}">—</b><span>Batería</span></div></div><button data-preview="${c}" style="width:100%;margin-top:8px">PREVIEW ${c.toUpperCase()}</button>`;g.appendChild(a)});g.querySelectorAll("[data-preview]").forEach(b=>b.onclick=()=>db.ref(`switcher/${game}/preview`).set(b.dataset.preview));}
async function closeCamera(c){const p=peers.get(c);if(!p)return;try{p.stop?.();p.answer.off();p.candidates.off();p.pc.close()}catch{}await Switcher.safeRemove(db.ref(p.base));peers.delete(c);$("video-"+c).srcObject=null;}
async function connectCamera(c){if(!online.has(c))return;await closeCamera(c);const id=`director-${client}-${c}-${Date.now().toString(36)}`,base=`switcher/${game}/cameraSignaling/${c}/${id}`,pc=new RTCPeerConnection(Switcher.peerConfig(ice)),q=Switcher.makeIceQueue(pc);pc.addTransceiver("video",{direction:"recvonly"});pc.addTransceiver("audio",{direction:"recvonly"});pc.ontrack=e=>{let s=$("video-"+c).srcObject;if(!s){s=e.streams[0]||new MediaStream();$("video-"+c).srcObject=s}if(!s.getTracks().some(t=>t.id===e.track.id))s.addTrack(e.track);$("video-"+c).play().catch(()=>{});paint();};let ready=false,pending=[];pc.onicecandidate=e=>{if(!e.candidate)return;const x=e.candidate.toJSON();ready?db.ref(`${base}/viewerCandidates`).push(x):pending.push(x)};pc.onconnectionstatechange=()=>{const el=$("state-"+c);el.textContent=pc.connectionState;el.className=`badge ${pc.connectionState==="connected"?"good":pc.connectionState==="failed"?"bad":"warn"}`;if(pc.connectionState==="failed"&&online.has(c))setTimeout(()=>connectCamera(c),1500)};const candidates=db.ref(`${base}/cameraCandidates`),answer=db.ref(`${base}/answer`);candidates.on("child_added",s=>s.val()&&q.add(s.val()));answer.on("value",async s=>{if(s.val()&&!pc.currentRemoteDescription){try{await pc.setRemoteDescription(s.val());await q.flush()}catch(e){log(`CAM ${c}: ${e.message}`)}}});await pc.setLocalDescription(await pc.createOffer());await db.ref(base).set({role:"director",clientId:client,createdAt:firebase.database.ServerValue.TIMESTAMP,offer:{type:pc.localDescription.type,sdp:pc.localDescription.sdp}});ready=true;for(const x of pending)await db.ref(`${base}/viewerCandidates`).push(x);const stop=Switcher.makeStatsReader(pc,s=>{$("bitrate-"+c).textContent=Switcher.formatBps(s.bitrate);$("rtt-"+c).textContent=Number.isFinite(s.rtt)?Math.round(s.rtt)+" ms":"—";$("fps-"+c).textContent=s.fps;$("res-"+c).textContent=s.width?`${s.width}×${s.height}`:"—"});peers.set(c,{pc,base,stop,answer,candidates});}
function paint(){cams.forEach(c=>{$("card-"+c).classList.toggle("program",c===program);$("card-"+c).classList.toggle("preview",c===preview&&c!==program)});$("previewLabel").textContent=`Preview: ${preview||"—"}`;$("programLabel").textContent=`Program: ${program||"—"}`;$("programName").textContent=program?program.toUpperCase():"Sin cámara al aire";$("previewName").textContent=preview?preview.toUpperCase():"Sin cámara seleccionada";$("previewMonitor").srcObject=preview?$("video-"+preview)?.srcObject||null:null;$("programMonitor").srcObject=program?$("video-"+program)?.srcObject||null:null;$("outputState").textContent=program?"PROGRAM directo a Broadcast":"Sin cámara PROGRAM";$("outputState").className=`badge ${program?"good":"warn"}`;$("blackLabel").textContent=`Black: ${isBlack?"sí":"no"}`;}
async function take(mode){if(!preview)return alert("Selecciona una cámara en PREVIEW");if(mode!=="cut")await db.ref(`switcher/${game}/transition`).set({type:mode,duration:Switcher.app.transitionMs||450,at:Date.now()});await db.ref(`switcher/${game}/program`).set(preview);if(mode!=="cut")setTimeout(()=>db.ref(`switcher/${game}/transition`).remove(),700)}
render();try{db=Switcher.initFirebase();ice=await Switcher.getIceServers({game,role:"director",clientId:client});$("infra").textContent="Firebase + TURN OK";$("infra").className="badge good";const dref=db.ref(`switcher/${game}/director`);await dref.onDisconnect().set({online:false,lastSeen:firebase.database.ServerValue.TIMESTAMP});const beat=()=>dref.set({online:true,lastSeen:firebase.database.ServerValue.TIMESTAMP,clientId:client,version:"11.0.0"});await beat();setInterval(beat,4000);const presenceSeen=new Map();
function applyPresence(c,v={}){const now=Date.now(),isOnline=v.online===true;if(isOnline)presenceSeen.set(c,now);const fresh=isOnline&&(now-(presenceSeen.get(c)||0)<(Switcher.app.cameraOfflineAfterMs||16000));$("presence-"+c).textContent=fresh?"En línea":"Sin señal";$("presence-"+c).className=`badge ${fresh?"good":"warn"}`;$("bat-"+c).textContent=Number.isFinite(+v.battery)&&+v.battery>0?`${v.battery}%`:"—";if(fresh&&!online.has(c)){online.add(c);connectCamera(c)}else if(!fresh&&online.has(c)){online.delete(c);closeCamera(c)}}
cams.forEach(c=>db.ref(`switcher/${game}/cameras/${c}`).on("value",s=>applyPresence(c,s.val()||{})));
setInterval(()=>cams.forEach(c=>{if(online.has(c)&&Date.now()-(presenceSeen.get(c)||0)>=(Switcher.app.cameraOfflineAfterMs||16000))applyPresence(c,{online:false})}),2000);db.ref(`switcher/${game}/preview`).on("value",s=>{preview=s.val()||"";paint()});db.ref(`switcher/${game}/program`).on("value",s=>{program=s.val()||"";paint();setTimeout(startPreviewBuffer,700)});db.ref(`switcher/${game}/black`).on("value",s=>{isBlack=!!s.val();paint()});db.ref(`switcher/${game}/broadcast/replayStatus`).on("value",s=>{const v=s.val()||{};$("replayReady").textContent=v.ready?`BUFFER ${Math.floor(v.bufferSeconds||0)}s`:v.supported===false?"NO COMPATIBLE":"ESPERANDO BUFFER";$("replayReady").className=`badge ${v.ready?"good":"warn"}`;$("replayState").textContent=v.playing?"Replay: AL AIRE":`Replay: ${v.message||"esperando Broadcast"}`});const code=encodeURIComponent(Switcher.getAccessCode());const live=`../broadcast/?game=${encodeURIComponent(game)}&v=1100&code=${code}`;$("liveLink").href=live;$("copyLive").onclick=()=>navigator.clipboard.writeText(new URL(live,location.href).href);$("overlayControl").href=Switcher.app.overlayControlUrl;db.ref(`switcher/${game}/broadcast/overlay`).on("value",s=>{const v=s.val()||{};let url=(v.url||Switcher.app.defaultOverlayUrl||"").trim();if(!url||/beisbol-overlay\.web\.app\/overlay\.html/i.test(url))url=new URL("../overlay/index.html?embedded=1",location.href).href;$("overlayUrl").value=url;$("overlayToggle").textContent=`OVERLAY: ${v.enabled===false?"OFF":"ON"}`});$("saveOverlay").onclick=()=>db.ref(`switcher/${game}/broadcast/overlay`).set({enabled:true,url:$("overlayUrl").value.trim(),updatedAt:Date.now()});$("clearOverlay").onclick=()=>db.ref(`switcher/${game}/broadcast/overlay`).set({enabled:false,url:"",updatedAt:Date.now()});$("overlayToggle").onclick=async()=>{const r=db.ref(`switcher/${game}/broadcast/overlay`),s=await r.once("value"),v=s.val()||{};await r.update({enabled:v.enabled===false,updatedAt:Date.now()})};$("cut").onclick=()=>take("cut");$("auto").onclick=()=>take("auto");$("fade").onclick=()=>take("fade");$("black").onclick=()=>db.ref(`switcher/${game}/black`).set(!isBlack);$("replayPreview").onclick=previewReplay;$("replaySend").onclick=sendReplayToAir;$("replayCancel").onclick=closeReplayPreview;$("replaySendFromPreview").onclick=sendReplayToAir;$("replayStop").onclick=()=>db.ref(`switcher/${game}/broadcast/replayCommand`).set({id:Date.now()+"-stop",action:"stop",at:Date.now()});$("reconnect").onclick=()=>cams.forEach(c=>online.has(c)&&connectCamera(c));$("clean").onclick=async()=>{await db.ref(`switcher/${game}/cameraSignaling`).remove();cams.forEach(c=>online.has(c)&&setTimeout(()=>connectCamera(c),500))};log("V11 listo: Broadcast conecta directamente a PROGRAM");}catch(e){$("infra").textContent="ERROR";$("infra").className="badge bad";log(e.message)}})();
