(()=>{
'use strict';
const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
const qs=new URLSearchParams(location.search); const game=(qs.get('game')||'partido1').replace(/[^a-zA-Z0-9_-]/g,'-'); $('gameTitle').textContent=game.toUpperCase();
$('clockNow').textContent=new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'}); setInterval(()=>$('clockNow').textContent=new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'}),1000);
const code=qs.get('code')||''; const v=qs.get('v')||'2200'; const engine=$('engine'); engine.src=`./index.html?game=${encodeURIComponent(game)}&v=${encodeURIComponent(v)}&code=${encodeURIComponent(code)}&embeddedMobile=1&desktop=1`;
let engineDoc=null, db=null, sport='baseball', bs={}, ss={}, cards={}, fadeMs=1000, clock={};
function mirror(){if(!engineDoc)return;const pairs=[['programMonitor','mProgram'],['previewMonitor','mPreview'],['video-cam1','mCam1'],['video-cam2','mCam2'],['video-cam3','mCam3']];for(const [srcId,dstId] of pairs){const s=engineDoc.getElementById(srcId),d=$(dstId);if(s&&d&&d.srcObject!==s.srcObject)d.srcObject=s.srcObject||null;}const pn=engineDoc.getElementById('programName')?.textContent||'—',pr=engineDoc.getElementById('previewName')?.textContent||'—';$('programName').textContent=pn;$('previewName').textContent=pr;for(const c of ['cam1','cam2','cam3']){$(`s${c[0].toUpperCase()+c.slice(1)}`).textContent=engineDoc.getElementById(`state-${c}`)?.textContent||'offline';}}
engine.addEventListener('load',()=>{try{engineDoc=engine.contentDocument;setInterval(mirror,300);mirror();}catch(e){console.warn(e)}});
function init(){if(!window.firebase||!window.Switcher)return;db=Switcher.initFirebase();const sw=db.ref(`switcher/${game}`), sportRef=sw.child('sport'), baseballRef=db.ref('gameState');$('firebaseState').textContent='FIREBASE ●';$('firebaseState').style.color='#2ee48c';
 sw.child('transitionSettings/fadeMs').on('value',s=>{fadeMs=Math.max(200,Math.min(5000,Number(s.val())||1000));$('fadeValue').textContent=(fadeMs/1000).toFixed(1)+'s'});
 sw.child('broadcast/replayTransition').on('value',s=>{const x=s.val()||{};$('stingerImg').src=x.url||`../assets/replay/${x.sport||'baseball'}.svg`});
 sw.child('program').on('value',s=>{const x=s.val()||'cam1';$$('[data-cam]').forEach(b=>b.classList.toggle('active',b.dataset.cam===x))});
 sportRef.on('value',s=>{ss=s.val()||{};sport=ss.current||'baseball';cards=ss.cards||{};clock=ss.clockControl||{};render()}); baseballRef.on('value',s=>{bs=s.val()||{};render()});
 const tx=(ref,delta,min,max)=>ref.transaction(v=>Math.max(min,Math.min(max,(Number(v)||0)+delta)));
 $$('[data-cam]').forEach(b=>b.onclick=()=>sw.child('preview').set(b.dataset.cam)); $$('[data-source]').forEach(b=>b.onclick=()=>sw.child('preview').set(b.dataset.source));
 $$('[data-score]').forEach(b=>b.onclick=()=>{const side=b.dataset.score,d=Number(b.dataset.delta);if(sport==='baseball')return tx(baseballRef.child(`${side}/score`),d,0,999);return tx(sportRef.child(`score/${side==='home'?'homeScore':'awayScore'}`),d,0,999)});
 $$('[data-count]').forEach(b=>b.onclick=()=>tx(baseballRef.child(b.dataset.count),Number(b.dataset.delta),0,b.dataset.count==='balls'?3:2));
 $$('[data-card]').forEach(b=>b.onclick=()=>tx(sportRef.child(`cards/${b.dataset.card}`),1,0,9));
 $$('[data-base]').forEach(b=>b.onclick=()=>baseballRef.child(`bases/${b.dataset.base}`).transaction(v=>!v)); $('clearBases').onclick=()=>baseballRef.child('bases').set({first:false,second:false,third:false});
 $('periodMinus').onclick=()=>sport==='baseball'?tx(baseballRef.child('inning'),-1,1,99):tx(sportRef.child('score/period'),-1,1,99); $('periodPlus').onclick=()=>sport==='baseball'?tx(baseballRef.child('inning'),1,1,99):tx(sportRef.child('score/period'),1,1,99);
 $('clockStart').onclick=()=>engineDoc?.getElementById('sportClockStart')?.click(); $('clockPause').onclick=()=>engineDoc?.getElementById('sportClockPause')?.click();
 $('fadeMinus').onclick=()=>sw.child('transitionSettings/fadeMs').set(Math.max(200,fadeMs-100)); $('fadePlus').onclick=()=>sw.child('transitionSettings/fadeMs').set(Math.min(5000,fadeMs+100));
 async function take(type){const p=(engineDoc?.getElementById('previewName')?.textContent||'').toLowerCase().match(/cam[123]/)?.[0];if(!p)return alert('Selecciona una cámara en PREVIEW');$('transitionName').textContent=type==='cut'?'CORTE':type.toUpperCase();if(type!=='cut')await sw.child('transition').set({type,duration:fadeMs,at:Date.now()});await sw.child('program').set(p);if(type!=='cut')setTimeout(()=>sw.child('transition').remove(),fadeMs+250)}
 $('cut').onclick=()=>take('cut');$('auto').onclick=()=>take('auto');$('fade').onclick=()=>take('fade');$('black').onclick=()=>sw.child('black').transaction(v=>!v);
 $('testStinger').onclick=()=>engineDoc?.getElementById('testReplayTransition')?.click();
 $$('[data-speed]').forEach(b=>b.onclick=()=>{$$('[data-speed]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const el=engineDoc?.getElementById('replaySpeed');if(el)el.value=b.dataset.speed});
 $$('[data-replay]').forEach(b=>b.onclick=()=>{const sec=Number(b.dataset.replay),max=Number(engineDoc?.getElementById('replayBufferLength')?.textContent)||30;const a=engineDoc?.getElementById('replayStart'),z=engineDoc?.getElementById('replayEnd');if(a)a.value=Math.max(0,max-sec);if(z)z.value=max;engineDoc?.getElementById('replayPreview')?.click()});
 $('replay').onclick=()=>engineDoc?.getElementById('replayPreview')?.click(); $('fullControl').onclick=()=>location.href=`./index.html?game=${encodeURIComponent(game)}&v=${encodeURIComponent(v)}&code=${encodeURIComponent(code)}&desktop=1`;
 $$('[data-tab]').forEach(b=>b.onclick=()=>location.href=`./index.html?game=${encodeURIComponent(game)}&v=${encodeURIComponent(v)}&code=${encodeURIComponent(code)}&desktop=1#${b.dataset.tab}`);
 setInterval(()=>{$('gameClock').textContent=calcClock()},250);
}
function calcClock(){let s=Number(clock.baseSeconds)||0;if(clock.running&&clock.startedAt){const e=(Date.now()-clock.startedAt)/1000;s=clock.mode==='countdown'?s-e:s+e}s=Math.max(0,Math.floor(s));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function logo(el,url){el.src=url||'';el.style.visibility=url?'visible':'hidden'}
function render(){const baseball=sport==='baseball',cfg=ss.config||{},sc=ss.score||{};if(baseball){const a=bs.away||{},h=bs.home||{};$('awayName').textContent=a.name||'VISITANTE';$('homeName').textContent=h.name||'LOCAL';$('awayScore').textContent=a.score||0;$('homeScore').textContent=h.score||0;logo($('awayLogo'),a.logo||cfg.awayLogo);logo($('homeLogo'),h.logo||cfg.homeLogo);$('periodValue').textContent=bs.inning||1;$('balls').textContent=bs.balls||0;$('strikes').textContent=bs.strikes||0;$('outs').textContent=bs.outs||0;const bases=bs.bases||{};$$('[data-base]').forEach(b=>b.classList.toggle('active',!!bases[b.dataset.base]));}else{$('awayName').textContent=cfg.awayName||'VISITANTE';$('homeName').textContent=cfg.homeName||'LOCAL';$('awayScore').textContent=sc.awayScore||0;$('homeScore').textContent=sc.homeScore||0;logo($('awayLogo'),cfg.awayLogo);logo($('homeLogo'),cfg.homeLogo);$('periodValue').textContent=sc.period||1;}const map={awayYellowCards:'awayYellow',awayRedCards:'awayRed',homeYellowCards:'homeYellow',homeRedCards:'homeRed'};for(const [k,id] of Object.entries(map))$(id).textContent=cards[k]||0;document.querySelector('.counts').style.visibility=baseball?'visible':'hidden';document.querySelector('.bases').style.visibility=baseball?'visible':'hidden'}
init();
})();
