(()=>{
  'use strict';
  const __q=new URLSearchParams(location.search);
  if(__q.get('desktop')==='1'||__q.get('embeddedMobile')==='1'||/mobile-v270\.html/i.test(location.pathname)) return;
  const isMobile=()=>/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent)||((navigator.maxTouchPoints||0)>0&&Math.min(screen.width,screen.height)<1100);
  if(!isMobile()) return;
  document.documentElement.classList.add('director-mobile-console');
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();

  ready(()=>{
    document.body.classList.add('director-mobile-console');
    const game=(window.Switcher?.normalizeId?.(window.Switcher?.qs?.('game',window.Switcher?.app?.defaultGame||'partido1')))||'partido1';
    const host=document.createElement('section');
    host.id='mobileBroadcastDirector';
    const shadow=host.attachShadow({mode:'open'});
    shadow.innerHTML=`
<style>
:host{position:fixed;inset:0;z-index:2147483000;display:block;width:100vw;height:100dvh;background:#02060d;overflow:hidden;color:#eef6ff;font-family:Arial,Helvetica,sans-serif}
*{box-sizing:border-box;min-width:0}button{border:1px solid #3b4d62;background:#182433;color:#fff;border-radius:6px;font-weight:900;padding:3px;touch-action:manipulation;cursor:pointer;-webkit-tap-highlight-color:transparent}button:active{filter:brightness(1.22);transform:translateY(1px)}
.stage{position:absolute;inset:0;display:grid;grid-template-rows:minmax(28px,5fr) minmax(142px,32fr) minmax(88px,19fr) minmax(132px,28fr) minmax(45px,10fr) minmax(28px,6fr);gap:clamp(4px,.55vh,7px);padding:clamp(5px,.65vh,8px);overflow:hidden;background:linear-gradient(180deg,#02060d,#07111e)}
.header{display:grid;grid-template-columns:minmax(72px,9%) minmax(55px,7%) 1fr minmax(85px,10%) auto minmax(55px,7%);align-items:center;gap:5px;padding:0 8px;background:#02050a;border:1px solid #182b42;border-radius:7px;font-size:clamp(8px,1.15vh,13px);overflow:hidden}.live{background:#e3192d;padding:4px 8px;border-radius:18px;text-align:center;font-weight:950}.title{text-align:center;font-size:clamp(13px,2vh,23px);font-weight:950;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.net{color:#41e98c}.cloud{text-align:right;white-space:nowrap}.infra.good{color:#24e58e}.infra.bad{color:#ff405b}.now{text-align:right;white-space:nowrap}.install{background:#067482;border-color:#2ee2ef;padding:3px 7px}
.top{display:grid;grid-template-columns:minmax(0,38fr) minmax(0,38fr) minmax(190px,24fr);gap:6px;min-height:0}.monitor,.side,.source,.replayQuick{background:#081321;border:1px solid #28445f;border-radius:8px;overflow:hidden}.monitor{display:grid;grid-template-rows:minmax(27px,16%) minmax(0,1fr);position:relative;padding:5px}.monitor.program{border-color:#e52d43}.monitor.preview{border-color:#16c978}.monitorHead{display:flex;justify-content:space-between;align-items:center}.monitorHead b,.monitorHead span{font-size:clamp(10px,1.6vh,18px);padding:4px 10px;border-radius:6px}.program .monitorHead b,.program .monitorHead span{background:#9d111f}.preview .monitorHead b,.preview .monitorHead span{background:#075c2e}.monitor video,.source video{width:100%;height:100%;object-fit:cover;background:#000;border-radius:4px}.monitor i{position:absolute;left:10px;bottom:9px;background:rgba(0,0,0,.72);padding:3px 7px;border-radius:4px;font-style:normal;font-size:clamp(7px,1vh,12px)}
.side{display:grid;grid-template-rows:auto minmax(34px,23%) minmax(38px,22%) minmax(38px,22%) minmax(54px,1fr);gap:5px;padding:6px;text-align:center}.side>b{font-size:clamp(8px,1.25vh,14px)}.camSelect{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.camSelect button{height:100%;font-size:clamp(9px,1.55vh,17px)}.camSelect button.active{background:#df1c2c;border-color:#ff6877}.transition{display:grid;place-content:center;border:1px solid #263d55;border-radius:5px}.transition small,.fadeDuration small,.stinger small{font-size:clamp(6px,.9vh,11px)}.transition strong{color:#29de87;font-size:clamp(11px,1.8vh,20px)}
.fadeDuration{display:grid;grid-template-rows:auto 1fr;gap:2px;border:1px solid #263d55;border-radius:5px;padding:3px}.fadeStepper{display:grid;grid-template-columns:1fr 2fr 1fr;align-items:center;gap:5px}.fadeStepper button{font-size:clamp(12px,2vh,22px)}.fadeStepper strong{font-size:clamp(12px,2vh,21px)}
.stinger{display:grid;grid-template-rows:auto minmax(0,1fr) minmax(28px,36%);gap:3px;border:1px solid #263d55;border-radius:5px;padding:4px}.stingerPreview{display:grid;grid-template-columns:1fr auto;align-items:center;gap:4px;background:#10192b;border-radius:4px;overflow:hidden}.stingerPreview img{width:100%;height:100%;max-height:40px;object-fit:contain}.stingerPreview span{padding:0 5px}.stinger>button{height:100%;background:#087735;border-color:#0fc45b;font-size:clamp(7px,1.1vh,13px)}
.sources{display:grid;grid-template-columns:repeat(3,minmax(0,22fr)) minmax(185px,34fr);gap:6px;min-height:0}.source{position:relative;padding:3px}.source b{position:absolute;left:7px;top:7px;background:#34465a;padding:3px 6px;border-radius:4px;font-size:clamp(7px,1.15vh,13px)}.source small{position:absolute;right:6px;bottom:5px;background:rgba(0,0,0,.72);padding:2px 5px;border-radius:4px;font-size:clamp(5px,.8vh,10px)}.source.on{border-color:#23d38a}.replayQuick{display:grid;grid-template-rows:auto 1fr auto 1fr;gap:4px;padding:6px;text-align:center;font-size:clamp(6px,.95vh,11px)}.replayQuick>div{display:grid;grid-template-columns:repeat(3,1fr);gap:4px}.replayQuick button{height:100%;font-size:clamp(7px,1.15vh,13px)}.replayQuick button.active{background:#008d4c}
.scoreboard{display:grid;grid-template-columns:minmax(0,36fr) minmax(0,28fr) minmax(0,36fr);width:100%;height:100%;background:linear-gradient(180deg,#fff,#f1f2f4);color:#0a0c0f;border:1px solid #cfd4da;border-radius:8px;overflow:hidden;contain:layout paint}.scoreboard article{display:grid;grid-template-rows:clamp(18px,2.5vh,25px) minmax(0,1fr) auto;width:100%;height:100%;padding:0 clamp(5px,.55vw,9px);border-right:1px solid #d7dade;overflow:hidden}.scoreboard article:last-child{border-right:0}.scoreboard h3{margin:0;text-align:center;line-height:clamp(18px,2.5vh,25px);font-size:clamp(10px,1.5vh,17px);font-weight:950;white-space:nowrap}
.teamBody{display:grid;grid-template-columns:minmax(42px,21%) minmax(29px,12%) minmax(0,67%);align-items:center;gap:clamp(3px,.4vw,7px);width:100%;height:100%;overflow:hidden}.team.home .teamBody{grid-template-columns:minmax(0,67%) minmax(42px,21%) minmax(29px,12%)}.team img{display:block;width:100%;height:clamp(48px,10.8vh,88px);object-fit:contain;margin:auto}.cards{display:grid;grid-template-rows:repeat(2,1fr);gap:clamp(2px,.4vh,5px);overflow:hidden}.cards button{display:grid;grid-template-columns:clamp(12px,1.7vh,20px) 1fr;align-items:center;gap:3px;width:100%;height:clamp(21px,3.35vh,32px);padding:0;background:transparent;border:0;color:#111;font-size:clamp(7px,1vh,12px)}.cards em{display:block;width:clamp(12px,1.7vh,20px);height:clamp(18px,2.7vh,27px);border:1px solid #333;border-radius:2px}.yellow{background:#ffd500}.red{background:#ed1c24}
.score{display:grid;grid-template-rows:minmax(32px,1fr) clamp(21px,3.3vh,30px) clamp(10px,1.6vh,16px);align-items:center;gap:clamp(2px,.3vh,4px);overflow:hidden}.scoreLine{display:grid;grid-template-columns:clamp(28px,3vw,42px) minmax(32px,1fr) clamp(28px,3vw,42px);align-items:center;gap:clamp(3px,.35vw,6px)}.scoreLine button{display:flex;align-items:center;justify-content:center;width:100%;height:clamp(28px,4.65vh,42px);padding:0;background:#e8e8e8;border-color:#a9adb2;color:#111;font-size:clamp(15px,2.6vh,24px)}.score strong{font-size:clamp(27px,5.6vh,50px);line-height:.92;text-align:center;color:#090b0e;overflow:hidden}.score small{font-size:clamp(6px,.9vh,10px);font-weight:900;text-align:center;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.quickScore{display:flex;align-items:center;justify-content:center;width:100%;height:clamp(21px,3.3vh,30px);padding:0 3px;background:#eee;border-color:#999;color:#111;font-size:clamp(6px,.83vh,9.5px);white-space:nowrap;overflow:hidden}
.center{grid-template-rows:clamp(18px,2.5vh,25px) minmax(36px,44%) minmax(0,1fr)!important}.period{display:grid;grid-template-columns:clamp(27px,2.8vw,40px) minmax(25px,1fr) clamp(27px,2.8vw,40px) clamp(27px,2.8vw,40px) clamp(27px,2.8vw,40px) minmax(61px,1.45fr);align-items:center;gap:clamp(2px,.3vw,5px);overflow:hidden}.period button{display:flex;align-items:center;justify-content:center;width:100%;height:clamp(27px,4.5vh,40px);padding:0;font-size:clamp(12px,2vh,19px)}.period strong{font-size:clamp(17px,3.1vh,28px);text-align:center}.period b{display:flex;align-items:center;justify-content:center;width:100%;height:clamp(27px,4.5vh,40px);padding:0 4px;background:#070707;color:#fff;border-radius:5px;font-size:clamp(13px,2.35vh,22px);font-variant-numeric:tabular-nums;white-space:nowrap;overflow:hidden}
.counts{display:grid;grid-template-columns:repeat(3,1fr);align-items:end;gap:clamp(3px,.4vw,6px);overflow:hidden}.counts label{display:grid;grid-template-columns:1fr 1fr 1fr;grid-template-rows:clamp(9px,1.35vh,14px) minmax(21px,1fr);align-items:center;gap:2px;font-size:clamp(5px,.75vh,9px);font-weight:950;text-align:center;overflow:hidden}.counts label>button:first-of-type{grid-column:1;grid-row:2}.counts label>strong{grid-column:2;grid-row:2}.counts label>button:last-of-type{grid-column:3;grid-row:2}.counts button,.counts strong{display:flex;align-items:center;justify-content:center;width:100%;height:clamp(21px,3.55vh,33px);padding:0;font-size:clamp(10px,1.75vh,17px)}.counts strong{border-radius:4px}.counts label:nth-child(1) strong{background:#14a85c;color:#fff}.counts label:nth-child(2) strong{background:#f5bf00;color:#fff}.counts label:nth-child(3) strong{background:#ee1c2d;color:#fff}
.bases{position:relative;display:block;width:clamp(88px,10vw,135px);height:clamp(42px,6.8vh,62px);margin-left:auto;overflow:visible}.baseBtn{position:absolute;width:clamp(25px,2.9vw,38px)!important;height:clamp(25px,2.9vw,38px)!important;min-width:0!important;padding:0!important;background:transparent!important;border:0!important;transform:rotate(45deg);border-radius:3px!important}.baseBtn:before{content:'';position:absolute;inset:2px;background:#292d32;border:2px solid #111;border-radius:3px;box-shadow:inset 0 0 0 1px #555}.baseBtn.active:before{background:#ffd51f;border-color:#c28f00;box-shadow:0 0 9px #ffd51f}.baseBtn span{position:relative;z-index:2;display:grid;place-items:center;width:100%;height:100%;transform:rotate(-45deg);font-size:clamp(6px,.85vh,10px);color:#fff}.baseBtn.active span{color:#111}.baseBtn.first{right:3%;bottom:2%}.baseBtn.second{left:50%;top:0;transform:translateX(-50%) rotate(45deg)}.baseBtn.third{left:3%;bottom:2%}.baseClear{position:absolute!important;right:0;bottom:0;transform:translateY(115%);height:clamp(18px,2.7vh,25px)!important;min-width:clamp(44px,5vw,70px)!important;background:#078c43!important;font-size:clamp(5px,.72vh,9px)!important}
.actions{display:grid;grid-template-columns:repeat(6,1fr);gap:6px}.actions button{height:100%;font-size:clamp(10px,1.75vh,19px)}.cut{background:#ad0d1c}.auto{background:#075eb4}.fade{background:#7b18a5}.black{background:#232a35}.replay{background:#9a7900}.full{background:#006c71}.nav{display:grid;grid-template-columns:repeat(5,1fr);gap:2px;background:#03070c}.nav button{height:100%;border:0;background:#07111d;color:#aab9c9;font-size:clamp(7px,1.2vh,13px)}.nav button:first-child{color:#1fe485;border-bottom:2px solid #1fe485}
@media(max-height:560px){.stage{grid-template-rows:27px 32fr 19fr 29fr 9fr 6fr}.quickScore{font-size:6px}.team img{height:45px}.side{grid-template-rows:auto 20% 20% 20% 1fr}.stingerPreview img{max-height:28px}}
</style>
<div class="stage">
<header class="header"><span class="live">EN VIVO</span><span class="net">● <b id="mbdLatency">—</b> ms</span><b class="title">DIRECTOR · ${game.toUpperCase()}</b><span class="cloud">FIREBASE</span><b class="infra" id="mbdInfra">●</b><span class="now" id="mbdTime"></span><button class="install" id="mbdInstall" hidden>INSTALAR</button></header>
<section class="top"><article class="monitor program"><div class="monitorHead"><b>PROGRAM</b><span>EN AIRE</span></div><video id="mbdProgram" autoplay muted playsinline></video><i id="mbdProgramName">—</i></article><article class="monitor preview"><div class="monitorHead"><b>PREVIEW</b><span>VISTA PREVIA</span></div><video id="mbdPreview" autoplay muted playsinline></video><i id="mbdPreviewName">—</i></article><aside class="side"><b>SELECCIÓN DE CÁMARA</b><div class="camSelect"><button data-cam-select="cam1">CAM1</button><button data-cam-select="cam2">CAM2</button><button data-cam-select="cam3">CAM3</button></div><div class="transition"><small>TRANSICIÓN ACTUAL</small><strong id="mbdTransition">CORTE</strong></div><div class="fadeDuration"><small>DURACIÓN FADE</small><div class="fadeStepper"><button id="mbdFadeMinus">−</button><strong id="mbdFadeValue">1.0s</strong><button id="mbdFadePlus">+</button></div></div><div class="stinger"><small>STINGER / TRANSICIÓN</small><div class="stingerPreview"><img id="mbdStingerImage" alt="Repetición"><span>⌄</span></div><button id="mbdTestStinger">PROBAR TRANSICIÓN</button></div></aside></section>
<section class="sources"><article class="source" data-source="cam1"><b>CAM1</b><video autoplay muted playsinline></video><small>OFFLINE</small></article><article class="source" data-source="cam2"><b>CAM2</b><video autoplay muted playsinline></video><small>OFFLINE</small></article><article class="source" data-source="cam3"><b>CAM3</b><video autoplay muted playsinline></video><small>OFFLINE</small></article><aside class="replayQuick"><b>REPLAY RÁPIDO</b><div><button data-replay-sec="5">5s</button><button data-replay-sec="10">10s</button><button data-replay-sec="15">15s</button></div><small>VELOCIDAD</small><div><button data-speed="0.25">0.25×</button><button data-speed="0.5">0.5×</button><button class="active" data-speed="1">1×</button></div></aside></section>
<section class="scoreboard"><article class="team away"><h3>VISITANTE</h3><div class="teamBody"><img id="mbdAwayLogo" alt="Logo visitante"><div class="cards"><button data-card="awayYellowCards" data-delta="1"><em class="yellow"></em><span id="mbdAwayYellow">0</span></button><button data-card="awayRedCards" data-delta="1"><em class="red"></em><span id="mbdAwayRed">0</span></button></div><div class="score"><div class="scoreLine"><button data-score="away" data-delta="-1">−</button><strong id="mbdAwayScore">0</strong><button data-score="away" data-delta="1">+</button></div><button class="quickScore" data-score="away" data-delta="1">+1 GOL / CARRERA</button><small id="mbdAwayName">VISITANTE</small></div></div></article><article class="center"><h3>PERIODO / RELOJ</h3><div class="period"><button id="mbdPeriodMinus">−</button><strong id="mbdPeriod">1</strong><button id="mbdPeriodPlus">+</button><button id="mbdClockStart">▶</button><button id="mbdClockPause">Ⅱ</button><b id="mbdClock">00:00</b></div><div class="counts" id="mbdCounts"><label>BOLAS <button data-count="balls" data-delta="-1">−</button><strong id="mbdBalls">0</strong><button data-count="balls" data-delta="1">+</button></label><label>STRIKES <button data-count="strikes" data-delta="-1">−</button><strong id="mbdStrikes">0</strong><button data-count="strikes" data-delta="1">+</button></label><label>OUTS <button data-count="outs" data-delta="-1">−</button><strong id="mbdOuts">0</strong><button data-count="outs" data-delta="1">+</button></label></div></article><article class="team home"><h3>LOCAL</h3><div class="teamBody"><div class="score"><div class="scoreLine"><button data-score="home" data-delta="-1">−</button><strong id="mbdHomeScore">0</strong><button data-score="home" data-delta="1">+</button></div><button class="quickScore" data-score="home" data-delta="1">+1 GOL / CARRERA</button><small id="mbdHomeName">LOCAL</small></div><img id="mbdHomeLogo" alt="Logo local"><div class="cards"><button data-card="homeYellowCards" data-delta="1"><em class="yellow"></em><span id="mbdHomeYellow">0</span></button><button data-card="homeRedCards" data-delta="1"><em class="red"></em><span id="mbdHomeRed">0</span></button></div></div><div class="bases" id="mbdBases"><button class="baseBtn first" data-base="first" aria-label="Primera base"><span>1B</span></button><button class="baseBtn second" data-base="second" aria-label="Segunda base"><span>2B</span></button><button class="baseBtn third" data-base="third" aria-label="Tercera base"><span>3B</span></button><button class="baseClear" id="mbdClearBases">LIMPIAR</button></div></article></section>
<section class="actions"><button class="cut" data-transition="cut">CUT</button><button class="auto" data-transition="auto">AUTO</button><button class="fade" data-transition="fade">FADE</button><button class="black" id="mbdBlack">BLACK</button><button class="replay" id="mbdReplay">REPLAY</button><button class="full" id="mbdFullControl">CONTROL COMPLETO</button></section>
<nav class="nav"><button data-open-tab="production">PRODUCCIÓN</button><button data-open-tab="replay">REPLAY</button><button data-open-tab="graphics">GRÁFICOS</button><button data-open-tab="media">MEDIOS</button><button data-open-tab="system">SISTEMA</button></nav>
</div>`;
    document.body.appendChild(host);
    const get=id=>shadow.getElementById(id), qsa=s=>[...shadow.querySelectorAll(s)], docGet=id=>document.getElementById(id);
    const back=document.createElement('button');back.id='mobileBackToQuick';back.type='button';back.textContent='← PANEL RÁPIDO';document.body.appendChild(back);
    const style=document.createElement('style');style.textContent=`#mobileBackToQuick{display:none;position:fixed;z-index:2147483600;top:max(8px,env(safe-area-inset-top));left:max(8px,env(safe-area-inset-left));width:auto!important;height:38px!important;min-width:132px!important;max-width:210px!important;padding:0 14px!important;border-radius:7px!important;border:1px solid #2ed7e5!important;background:#087786!important;color:white!important;font:800 12px/38px Arial!important;box-shadow:0 4px 14px #0008!important}.mobile-full-control #mobileBackToQuick{display:block!important}.mobile-full-control #mobileBroadcastDirector{display:none!important}.director-mobile-console:not(.mobile-full-control) body>main,.director-mobile-console:not(.mobile-full-control) body>.phone-view-note,.director-mobile-console:not(.mobile-full-control) body>.v15-status-dock{visibility:hidden!important}.director-mobile-console.mobile-full-control body{overflow:auto!important}`;document.head.appendChild(style);

    const syncVideo=(dst,src)=>{if(!dst||!src)return;try{if(src.srcObject&&dst.srcObject!==src.srcObject){dst.srcObject=src.srcObject;dst.play().catch(()=>{})}else if(!src.srcObject&&src.currentSrc&&dst.src!==src.currentSrc){dst.src=src.currentSrc;dst.play().catch(()=>{})}}catch(_){}};
    const cardFor=id=>document.querySelector(`[data-camera-card="${id}"]`)||docGet(`card-${id}`)||docGet(id)?.closest('.source-card,.camera-card,.panel');
    function syncMonitors(){syncVideo(get('mbdProgram'),docGet('programMonitor'));syncVideo(get('mbdPreview'),docGet('previewMonitor'));get('mbdProgramName').textContent=docGet('programName')?.textContent||'—';get('mbdPreviewName').textContent=docGet('previewName')?.textContent||'—';qsa('.source').forEach(el=>{const id=el.dataset.source,card=cardFor(id),video=card?.querySelector('video');syncVideo(el.querySelector('video'),video);el.querySelector('small').textContent=docGet('state-'+id)?.textContent||'OFFLINE';el.classList.toggle('on',docGet('state-'+id)?.textContent?.toLowerCase().includes('connect'))});const p=(docGet('programName')?.textContent||'').toLowerCase();qsa('[data-cam-select]').forEach(b=>b.classList.toggle('active',p.includes(b.dataset.camSelect)));const infra=docGet('infra');get('mbdInfra').className=infra?.classList.contains('bad')?'infra bad':infra?.classList.contains('good')?'infra good':'infra'}
    setInterval(syncMonitors,700);setInterval(()=>get('mbdTime').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),1000);syncMonitors();
    let deferredInstall=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;get('mbdInstall').hidden=false});get('mbdInstall').onclick=async()=>{if(!deferredInstall){alert('En Chrome abre el menú ⋮ y selecciona Instalar aplicación.');return}deferredInstall.prompt();await deferredInstall.userChoice.catch(()=>null);deferredInstall=null;get('mbdInstall').hidden=true};
    const cameraPreview=id=>document.querySelector(`[data-preview="${id}"]`)?.click();qsa('[data-cam-select]').forEach(b=>b.onclick=()=>cameraPreview(b.dataset.camSelect));qsa('.source').forEach(b=>b.onclick=()=>cameraPreview(b.dataset.source));get('mbdTestStinger').onclick=()=>docGet('testReplayTransition')?.click();
    qsa('[data-speed]').forEach(b=>b.onclick=()=>{qsa('[data-speed]').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(docGet('replaySpeed'))docGet('replaySpeed').value=b.dataset.speed});qsa('[data-replay-sec]').forEach(b=>b.onclick=()=>{const sec=+b.dataset.replaySec,max=+(docGet('replayBufferLength')?.textContent||30)||30,start=Math.max(0,max-sec);if(docGet('replayStart'))docGet('replayStart').value=start;if(docGet('replayEnd'))docGet('replayEnd').value=max;docGet('replayPreview')?.click()});
    function openFull(tab){document.body.classList.add('mobile-full-control');document.querySelector(`[data-v15-tab="${tab}"]`)?.click();window.scrollTo(0,0)}function returnQuick(){document.body.classList.remove('mobile-full-control');window.scrollTo(0,0)}get('mbdReplay').onclick=()=>docGet('replayPreview')?.click()||openFull('replay');get('mbdFullControl').onclick=()=>openFull('production');qsa('[data-open-tab]').forEach(b=>b.onclick=()=>openFull(b.dataset.openTab));back.onclick=returnQuick;
    if(!window.firebase||!window.Switcher){host.dataset.diagnostics='firebase-or-switcher-missing';return}
    const db=Switcher.initFirebase(),sportRef=db.ref(`switcher/${game}/sport`),baseballRef=db.ref('gameState'),switcherRef=db.ref(`switcher/${game}`);let sport='baseball',ss={},bs={},cards={},clock={running:false,mode:'countup',baseSeconds:0,startedAt:0},fadeMs=1000,black=false;
    const clamp=(n,a=0,b=999)=>Math.max(a,Math.min(b,Number(n)||0)),fmt=s=>{s=Math.max(0,Math.floor(s));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`},clockSec=()=>{let s=+clock.baseSeconds||0;if(clock.running&&clock.startedAt){const e=Math.max(0,(Date.now()-clock.startedAt)/1000);s=clock.mode==='countdown'?s-e:s+e}return Math.max(0,s)};const logo=(el,url)=>{if(!el)return;el.src=url||'';el.style.visibility=url?'visible':'hidden'};
    function render(){const baseball=sport==='baseball',cfg=ss.config||{},sc=ss.score||{};get('mbdCounts').hidden=!baseball;get('mbdBases').hidden=!baseball;if(baseball){const a=bs.away||{},h=bs.home||{};get('mbdAwayName').textContent=a.name||'VISITANTE';get('mbdHomeName').textContent=h.name||'LOCAL';get('mbdAwayScore').textContent=a.score??0;get('mbdHomeScore').textContent=h.score??0;logo(get('mbdAwayLogo'),a.logo||cfg.awayLogo);logo(get('mbdHomeLogo'),h.logo||cfg.homeLogo);get('mbdPeriod').textContent=`${bs.inning||1} ${(bs.inningSide||'').replace('ALTA','▲').replace('BAJA','▼')}`;get('mbdBalls').textContent=bs.balls||0;get('mbdStrikes').textContent=bs.strikes||0;get('mbdOuts').textContent=bs.outs||0;const bases=bs.bases||{};qsa('[data-base]').forEach(b=>b.classList.toggle('active',!!bases[b.dataset.base]))}else{get('mbdAwayName').textContent=cfg.awayName||'VISITANTE';get('mbdHomeName').textContent=cfg.homeName||'LOCAL';get('mbdAwayScore').textContent=sc.awayScore??0;get('mbdHomeScore').textContent=sc.homeScore??0;logo(get('mbdAwayLogo'),cfg.awayLogo);logo(get('mbdHomeLogo'),cfg.homeLogo);get('mbdPeriod').textContent=sc.period??1}const map={awayYellowCards:'mbdAwayYellow',awayRedCards:'mbdAwayRed',homeYellowCards:'mbdHomeYellow',homeRedCards:'mbdHomeRed'};Object.entries(map).forEach(([k,id])=>get(id).textContent=cards[k]||0)}
    sportRef.on('value',s=>{ss=s.val()||{};sport=ss.current||'baseball';render()});sportRef.child('cards').on('value',s=>{cards=s.val()||{};render()});sportRef.child('clockControl').on('value',s=>clock={...clock,...(s.val()||{})});baseballRef.on('value',s=>{bs=s.val()||{};render()});switcherRef.child('black').on('value',s=>black=!!s.val());switcherRef.child('transitionSettings/fadeMs').on('value',s=>{fadeMs=clamp(s.val()||1000,200,5000);get('mbdFadeValue').textContent=(fadeMs/1000).toFixed(1)+'s'});switcherRef.child('broadcast/replayTransition').on('value',s=>{const v=s.val()||{},sportName=v.sport||'baseball';get('mbdStingerImage').src=v.url||new URL(`../assets/replay/${sportName}.svg`,location.href).href});setInterval(()=>get('mbdClock').textContent=fmt(clockSec()),250);
    const tx=(ref,delta,min,max)=>ref.transaction(v=>clamp((Number(v)||0)+delta,min,max));
    qsa('[data-score]').forEach(b=>b.onclick=async()=>{const side=b.dataset.score,d=+b.dataset.delta;if(sport==='baseball')await tx(baseballRef.child(`${side}/score`),d,0,999);else{const key=side==='home'?'homeScore':'awayScore';await tx(sportRef.child(`score/${key}`),d,0,999)}});
    qsa('[data-count]').forEach(b=>b.onclick=async()=>{const k=b.dataset.count,max=k==='balls'?3:2;await tx(baseballRef.child(k),+b.dataset.delta,0,max)});
    qsa('[data-card]').forEach(b=>b.onclick=async()=>{await tx(sportRef.child(`cards/${b.dataset.card}`),+b.dataset.delta,0,9)});
    qsa('[data-base]').forEach(b=>b.onclick=()=>baseballRef.child(`bases/${b.dataset.base}`).transaction(v=>!v));get('mbdClearBases').onclick=()=>baseballRef.child('bases').set({first:false,second:false,third:false});
    const periodDelta=async d=>{if(sport==='baseball')await tx(baseballRef.child('inning'),d,1,99);else await sportRef.child('score/period').transaction(v=>String(clamp((parseInt(v)||1)+d,1,99)))};get('mbdPeriodMinus').onclick=()=>periodDelta(-1);get('mbdPeriodPlus').onclick=()=>periodDelta(1);get('mbdClockStart').onclick=()=>docGet('sportClockStart')?.click();get('mbdClockPause').onclick=()=>docGet('sportClockPause')?.click();
    get('mbdFadeMinus').onclick=()=>switcherRef.child('transitionSettings/fadeMs').set(clamp(fadeMs-100,200,5000));get('mbdFadePlus').onclick=()=>switcherRef.child('transitionSettings/fadeMs').set(clamp(fadeMs+100,200,5000));
    const take=async mode=>{const preview=(docGet('previewName')?.textContent||'').trim().toLowerCase();const cam=/cam[123]/.exec(preview)?.[0];if(!cam){alert('Selecciona una cámara en PREVIEW');return}get('mbdTransition').textContent=mode==='cut'?'CORTE':mode.toUpperCase();if(mode!=='cut')await switcherRef.child('transition').set({type:mode,duration:fadeMs,at:Date.now()});await switcherRef.child('program').set(cam);if(mode!=='cut')setTimeout(()=>switcherRef.child('transition').remove(),fadeMs+250)};qsa('[data-transition]').forEach(b=>b.onclick=()=>take(b.dataset.transition));get('mbdBlack').onclick=()=>switcherRef.child('black').set(!black);
    const required=['mbdFadeMinus','mbdFadePlus','mbdTestStinger','mbdClearBases','mbdPeriodMinus','mbdPeriodPlus','mbdClockStart','mbdClockPause','mbdBlack','mbdReplay','mbdFullControl'];const missing=required.filter(id=>!get(id)||typeof get(id).onclick!=='function');host.dataset.diagnostics=missing.length?'missing:'+missing.join(','):'ok';window.__switcherMobileDiagnostics={version:'21.0',missing,buttons:shadow.querySelectorAll('button').length};
  });
})();
