(()=>{"use strict";
const isMobile=()=>/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent)||((navigator.maxTouchPoints||0)>0&&Math.min(screen.width,screen.height)<1000);
if(!isMobile())return;
document.documentElement.classList.add("director-mobile-console");
const ready=fn=>document.readyState==="loading"?document.addEventListener("DOMContentLoaded",fn,{once:true}):fn();
ready(()=>{
 document.body.classList.add("director-mobile-console");
 const host=document.createElement("section");host.id="mobileBroadcastDirector";host.className="mobile-broadcast-director";
 const shadow=host.attachShadow({mode:"open"});
 shadow.innerHTML=`<style>
 :host{position:fixed;inset:0;z-index:2147483000;display:block;width:100vw;height:100dvh;background:#02060d;overflow:hidden;color:#eef6ff;font-family:Arial,Helvetica,sans-serif}
 *{box-sizing:border-box;min-width:0}button{border:1px solid #3b4d62;background:#182433;color:#fff;border-radius:6px;font-weight:900;padding:3px;touch-action:manipulation;cursor:pointer}button:active{filter:brightness(1.18)}
 .stage{position:absolute;inset:0;display:grid;grid-template-rows:minmax(28px,5fr) minmax(150px,34fr) minmax(90px,20fr) minmax(130px,26fr) minmax(45px,9fr) minmax(28px,6fr);gap:clamp(4px,.55vh,7px);padding:clamp(5px,.65vh,8px);overflow:hidden;background:linear-gradient(180deg,#02060d,#07111e)}
 .header{display:grid;grid-template-columns:minmax(72px,9%) minmax(55px,7%) 1fr minmax(85px,10%) auto minmax(55px,7%);align-items:center;gap:5px;padding:0 8px;background:#02050a;border:1px solid #182b42;border-radius:7px;font-size:clamp(8px,1.15vh,13px);overflow:hidden}.live{background:#e3192d;padding:4px 8px;border-radius:18px;text-align:center;font-weight:950}.title{text-align:center;font-size:clamp(13px,2vh,23px);font-weight:950;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.net{color:#41e98c}.cloud{text-align:right;white-space:nowrap}.infra.good{color:#24e58e}.infra.bad{color:#ff405b}.now{text-align:right;white-space:nowrap}.install{background:#067482;border-color:#2ee2ef;padding:3px 7px}
 .top{display:grid;grid-template-columns:minmax(0,38fr) minmax(0,38fr) minmax(175px,24fr);gap:6px;min-height:0}.monitor,.side,.source,.replayQuick{background:#081321;border:1px solid #28445f;border-radius:8px;overflow:hidden}.monitor{display:grid;grid-template-rows:minmax(27px,16%) minmax(0,1fr);position:relative;padding:5px}.monitor.program{border-color:#e52d43}.monitor.preview{border-color:#16c978}.monitorHead{display:flex;justify-content:space-between;align-items:center}.monitorHead b,.monitorHead span{font-size:clamp(10px,1.6vh,18px);padding:4px 10px;border-radius:6px}.program .monitorHead b,.program .monitorHead span{background:#9d111f}.preview .monitorHead b,.preview .monitorHead span{background:#075c2e}.monitor video,.source video{width:100%;height:100%;object-fit:cover;background:#000;border-radius:4px}.monitor i{position:absolute;left:10px;bottom:9px;background:rgba(0,0,0,.72);padding:3px 7px;border-radius:4px;font-style:normal;font-size:clamp(7px,1vh,12px)}
 .side{display:grid;grid-template-rows:auto minmax(34px,28%) minmax(42px,34%) minmax(34px,1fr);gap:5px;padding:6px;text-align:center}.side>b{font-size:clamp(8px,1.25vh,14px)}.camSelect{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.camSelect button{height:100%;font-size:clamp(9px,1.55vh,17px)}.camSelect button.active{background:#df1c2c;border-color:#ff6877}.transition{display:grid;place-content:center;border:1px solid #263d55;border-radius:5px}.transition small,.stinger small{font-size:clamp(6px,.9vh,11px)}.transition strong{color:#29de87;font-size:clamp(11px,1.8vh,20px)}.stinger{display:grid;grid-template-rows:auto 1fr;gap:3px}.stinger button{height:100%;background:#087735;font-size:clamp(7px,1.1vh,13px)}
 .sources{display:grid;grid-template-columns:repeat(3,minmax(0,22fr)) minmax(185px,34fr);gap:6px;min-height:0}.source{position:relative;padding:3px}.source b{position:absolute;left:7px;top:7px;background:#34465a;padding:3px 6px;border-radius:4px;font-size:clamp(7px,1.15vh,13px)}.source small{position:absolute;right:6px;bottom:5px;background:rgba(0,0,0,.72);padding:2px 5px;border-radius:4px;font-size:clamp(5px,.8vh,10px)}.source.on{border-color:#23d38a}.replayQuick{display:grid;grid-template-rows:auto 1fr auto 1fr;gap:4px;padding:6px;text-align:center;font-size:clamp(6px,.95vh,11px)}.replayQuick>div{display:grid;grid-template-columns:repeat(3,1fr);gap:4px}.replayQuick button{height:100%;font-size:clamp(7px,1.15vh,13px)}.replayQuick button.active{background:#008d4c}
 .scoreboard{display:grid;grid-template-columns:minmax(0,36fr) minmax(0,28fr) minmax(0,36fr);width:100%;height:100%;background:linear-gradient(180deg,#fff,#f1f2f4);color:#0a0c0f;border:1px solid #cfd4da;border-radius:8px;overflow:hidden;contain:layout paint}
 .scoreboard article{display:grid;grid-template-rows:clamp(18px,2.5vh,25px) minmax(0,1fr) auto;width:100%;height:100%;padding:0 clamp(5px,.55vw,9px);border-right:1px solid #d7dade;overflow:hidden}.scoreboard article:last-child{border-right:0}.scoreboard h3{margin:0;text-align:center;line-height:clamp(18px,2.5vh,25px);font-size:clamp(10px,1.5vh,17px);font-weight:950;white-space:nowrap}
 .teamBody{display:grid;grid-template-columns:minmax(42px,21%) minmax(29px,12%) minmax(0,67%);align-items:center;gap:clamp(3px,.4vw,7px);width:100%;height:100%;overflow:hidden}.team.home .teamBody{grid-template-columns:minmax(0,67%) minmax(42px,21%) minmax(29px,12%)}.team img{display:block;width:100%;height:clamp(48px,10.8vh,88px);object-fit:contain;margin:auto}.cards{display:grid;grid-template-rows:repeat(2,1fr);gap:clamp(2px,.4vh,5px);overflow:hidden}.cards button{display:grid;grid-template-columns:clamp(12px,1.7vh,20px) 1fr;align-items:center;gap:3px;width:100%;height:clamp(21px,3.35vh,32px);padding:0;background:transparent;border:0;color:#111;font-size:clamp(7px,1vh,12px)}.cards em{display:block;width:clamp(12px,1.7vh,20px);height:clamp(18px,2.7vh,27px);border:1px solid #333;border-radius:2px}.yellow{background:#ffd500}.red{background:#ed1c24}
 .score{display:grid;grid-template-rows:minmax(32px,1fr) clamp(21px,3.3vh,30px) clamp(10px,1.6vh,16px);align-items:center;gap:clamp(2px,.3vh,4px);overflow:hidden}.scoreLine{display:grid;grid-template-columns:clamp(28px,3vw,42px) minmax(32px,1fr) clamp(28px,3vw,42px);align-items:center;gap:clamp(3px,.35vw,6px)}.scoreLine button{display:flex;align-items:center;justify-content:center;width:100%;height:clamp(28px,4.65vh,42px);padding:0;background:#e8e8e8;border-color:#a9adb2;color:#111;font-size:clamp(15px,2.6vh,24px)}.score strong{font-size:clamp(27px,5.6vh,50px);line-height:.92;text-align:center;color:#090b0e;overflow:hidden}.score small{font-size:clamp(6px,.9vh,10px);font-weight:900;text-align:center;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.quickScore{display:flex;align-items:center;justify-content:center;width:100%;height:clamp(21px,3.3vh,30px);padding:0 3px;background:#eee;border-color:#999;color:#111;font-size:clamp(6px,.83vh,9.5px);white-space:nowrap;overflow:hidden}
 .center{grid-template-rows:clamp(18px,2.5vh,25px) minmax(36px,44%) minmax(0,1fr)!important}.period{display:grid;grid-template-columns:clamp(27px,2.8vw,40px) minmax(25px,1fr) clamp(27px,2.8vw,40px) clamp(27px,2.8vw,40px) clamp(27px,2.8vw,40px) minmax(61px,1.45fr);align-items:center;gap:clamp(2px,.3vw,5px);overflow:hidden}.period button{display:flex;align-items:center;justify-content:center;width:100%;height:clamp(27px,4.5vh,40px);padding:0;font-size:clamp(12px,2vh,19px)}.period strong{font-size:clamp(17px,3.1vh,28px);text-align:center}.period b{display:flex;align-items:center;justify-content:center;width:100%;height:clamp(27px,4.5vh,40px);padding:0 4px;background:#070707;color:#fff;border-radius:5px;font-size:clamp(13px,2.35vh,22px);font-variant-numeric:tabular-nums;white-space:nowrap;overflow:hidden}
 .counts{display:grid;grid-template-columns:repeat(3,1fr);align-items:end;gap:clamp(3px,.4vw,6px);overflow:hidden}.counts label{display:grid;grid-template-columns:1fr 1fr 1fr;grid-template-rows:clamp(9px,1.35vh,14px) minmax(21px,1fr);align-items:center;gap:2px;font-size:clamp(5px,.75vh,9px);font-weight:950;text-align:center;overflow:hidden}.counts label>button:first-of-type{grid-column:1;grid-row:2}.counts label>strong{grid-column:2;grid-row:2}.counts label>button:last-of-type{grid-column:3;grid-row:2}.counts button,.counts strong{display:flex;align-items:center;justify-content:center;width:100%;height:clamp(21px,3.55vh,33px);padding:0;font-size:clamp(10px,1.75vh,17px)}.counts strong{border-radius:4px}.counts label:nth-child(1) strong{background:#14a85c;color:#fff}.counts label:nth-child(2) strong{background:#f5bf00;color:#fff}.counts label:nth-child(3) strong{background:#ee1c2d;color:#fff}
 .bases{display:flex;align-items:center;justify-content:flex-end;gap:clamp(2px,.25vw,4px);width:100%;min-height:clamp(20px,3.15vh,29px);overflow:hidden;white-space:nowrap}.bases:before{content:'◆ BASES';font-size:clamp(5px,.72vh,8.5px);font-weight:950;color:#111}.bases button{display:flex;align-items:center;justify-content:center;height:clamp(19px,3.05vh,28px);min-width:clamp(23px,2.45vw,36px);padding:0 clamp(3px,.3vw,6px);background:#252a31;color:#fff;border-color:#111;font-size:clamp(6px,.9vh,10px)}.bases button.active{background:#f7cf18;color:#000}.bases .clear{background:#078c43;min-width:auto}
 .actions{display:grid;grid-template-columns:repeat(6,1fr);gap:6px}.actions button{height:100%;font-size:clamp(10px,1.75vh,19px)}.cut{background:#ad0d1c}.auto{background:#075eb4}.fade{background:#7b18a5}.black{background:#232a35}.replay{background:#9a7900}.full{background:#006c71}.nav{display:grid;grid-template-columns:repeat(5,1fr);gap:2px;background:#03070c}.nav button{height:100%;border:0;background:#07111d;color:#aab9c9;font-size:clamp(7px,1.2vh,13px)}.nav button:first-child{color:#1fe485;border-bottom:2px solid #1fe485}
 @media(max-height:560px){.stage{grid-template-rows:27px 33fr 19fr 27fr 9fr 6fr}.quickScore{font-size:5.8px}.team img{height:9.8vh}}
 </style><div class="stage">
 <header class="header"><div class="live">EN VIVO</div><div class="net">● <span id="mbdLatency">— ms</span></div><div class="title">DIRECTOR · <span id="mbdGame">PARTIDO</span></div><div class="cloud">FIREBASE <span id="mbdInfra">●</span></div><button id="mbdInstall" class="install" hidden>INSTALAR</button><div class="now" id="mbdNow">--:--</div></header>
 <div class="top"><article class="monitor program"><div class="monitorHead"><b>PROGRAM</b><span>EN AIRE</span></div><video id="mbdProgram" autoplay muted playsinline></video><i id="mbdProgramName">—</i></article><article class="monitor preview"><div class="monitorHead"><b>PREVIEW</b><span>VISTA PREVIA</span></div><video id="mbdPreview" autoplay muted playsinline></video><i id="mbdPreviewName">—</i></article><aside class="side"><b>SELECCIÓN DE CÁMARA</b><div class="camSelect"><button data-cam-select="cam1">CAM1</button><button data-cam-select="cam2">CAM2</button><button data-cam-select="cam3">CAM3</button></div><div class="transition"><small>TRANSICIÓN ACTUAL</small><strong id="mbdTransition">CORTE</strong></div><div class="stinger"><small>STINGER / TRANSICIÓN</small><button id="mbdTestStinger">▶ PROBAR TRANSICIÓN</button></div></aside></div>
 <div class="sources"><div class="source" data-source="cam1"><video autoplay muted playsinline></video><b>CAM1</b><small>—</small></div><div class="source" data-source="cam2"><video autoplay muted playsinline></video><b>CAM2</b><small>—</small></div><div class="source" data-source="cam3"><video autoplay muted playsinline></video><b>CAM3</b><small>—</small></div><section class="replayQuick"><b>REPLAY RÁPIDO</b><div><button data-replay-sec="5">5s</button><button data-replay-sec="10">10s</button><button data-replay-sec="15">15s</button></div><small>VELOCIDAD</small><div><button data-speed="0.25">0.25×</button><button data-speed="0.5">0.5×</button><button class="active" data-speed="1">1×</button></div></section></div>
 <section class="scoreboard"><article class="team away"><h3>VISITANTE</h3><div class="teamBody"><img id="mbdAwayLogo" alt="Logo visitante"><div class="cards"><button data-card="awayYellowCards" data-delta="1"><em class="yellow"></em><span id="mbdAwayYellow">0</span></button><button data-card="awayRedCards" data-delta="1"><em class="red"></em><span id="mbdAwayRed">0</span></button></div><div class="score"><div class="scoreLine"><button data-score="away" data-delta="-1">−</button><strong id="mbdAwayScore">0</strong><button data-score="away" data-delta="1">+</button></div><button class="quickScore" data-score="away" data-delta="1">+1 GOL / CARRERA</button><small id="mbdAwayName">VISITANTE</small></div></div></article><article class="center"><h3>PERIODO / RELOJ</h3><div class="period"><button id="mbdPeriodMinus">−</button><strong id="mbdPeriod">1</strong><button id="mbdPeriodPlus">+</button><button id="mbdClockStart">▶</button><button id="mbdClockPause">Ⅱ</button><b id="mbdClock">00:00</b></div><div class="counts" id="mbdCounts"><label>BOLAS <button data-count="balls" data-delta="-1">−</button><strong id="mbdBalls">0</strong><button data-count="balls" data-delta="1">+</button></label><label>STRIKES <button data-count="strikes" data-delta="-1">−</button><strong id="mbdStrikes">0</strong><button data-count="strikes" data-delta="1">+</button></label><label>OUTS <button data-count="outs" data-delta="-1">−</button><strong id="mbdOuts">0</strong><button data-count="outs" data-delta="1">+</button></label></div></article><article class="team home"><h3>LOCAL</h3><div class="teamBody"><div class="score"><div class="scoreLine"><button data-score="home" data-delta="-1">−</button><strong id="mbdHomeScore">0</strong><button data-score="home" data-delta="1">+</button></div><button class="quickScore" data-score="home" data-delta="1">+1 GOL / CARRERA</button><small id="mbdHomeName">LOCAL</small></div><img id="mbdHomeLogo" alt="Logo local"><div class="cards"><button data-card="homeYellowCards" data-delta="1"><em class="yellow"></em><span id="mbdHomeYellow">0</span></button><button data-card="homeRedCards" data-delta="1"><em class="red"></em><span id="mbdHomeRed">0</span></button></div></div><div class="bases" id="mbdBases"><button data-base="first">1B</button><button data-base="second">2B</button><button data-base="third">3B</button><button class="clear" id="mbdClearBases">LIMPIAR</button></div></article></section>
 <div class="actions"><button class="cut" data-action="cut">CUT</button><button class="auto" data-action="auto">AUTO</button><button class="fade" data-action="fade">FADE</button><button class="black" data-action="black">BLACK</button><button class="replay" id="mbdReplay">REPLAY</button><button class="full" id="mbdFullControl">CONTROL COMPLETO</button></div><nav class="nav"><button data-open-tab="production">PRODUCCIÓN</button><button data-open-tab="replay">REPLAY</button><button data-open-tab="graphics">GRÁFICOS</button><button data-open-tab="media">MEDIOS</button><button data-open-tab="system">SISTEMA</button></nav>
 </div>`;
 document.body.appendChild(host);
 const get=id=>shadow.getElementById(id)||document.getElementById(id), qs=(s,r=shadow)=>r.querySelector(s), qsa=(s,r=shadow)=>[...r.querySelectorAll(s)];
 const back=document.createElement("button");back.id="mbdBack";back.className="mbd-back";back.textContent="← VOLVER AL PANEL RÁPIDO";document.body.appendChild(back);
 const game=(window.Switcher&&Switcher.normalizeId(Switcher.qs("game",Switcher.app.defaultGame)))||"partido1";get("mbdGame").textContent=game.toUpperCase();
 try{localStorage.setItem("switcherDirectorLaunchUrl",location.href)}catch(_){}
 let deferredInstall=null;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;get("mbdInstall").hidden=false});get("mbdInstall").onclick=async()=>{if(!deferredInstall){alert("En Chrome abre el menú ⋮ y selecciona Instalar aplicación.");return}deferredInstall.prompt();await deferredInstall.userChoice.catch(()=>null);deferredInstall=null;get("mbdInstall").hidden=true};
 const syncVideo=(dst,src)=>{if(dst&&src?.srcObject&&dst.srcObject!==src.srcObject){dst.srcObject=src.srcObject;dst.play().catch(()=>{})}};const docGet=id=>document.getElementById(id);const cardFor=id=>docGet("card-"+id)?.closest("article")||docGet("card-"+id);
 function syncMonitors(){syncVideo(get("mbdProgram"),docGet("programMonitor"));syncVideo(get("mbdPreview"),docGet("previewMonitor"));get("mbdProgramName").textContent=docGet("programName")?.textContent||"—";get("mbdPreviewName").textContent=docGet("previewName")?.textContent||"—";qsa(".source").forEach(el=>{const id=el.dataset.source,card=cardFor(id),video=card?.querySelector("video");syncVideo(el.querySelector("video"),video);el.querySelector("small").textContent=docGet("state-"+id)?.textContent||"OFFLINE";el.classList.toggle("on",docGet("state-"+id)?.textContent?.toLowerCase().includes("connect"))});const p=(docGet("programName")?.textContent||"").toLowerCase();qsa("[data-cam-select]").forEach(b=>b.classList.toggle("active",p.includes(b.dataset.camSelect)));const infra=docGet("infra");get("mbdInfra").className=infra?.classList.contains("bad")?"infra bad":infra?.classList.contains("good")?"infra good":"infra"}
 setInterval(syncMonitors,400);syncMonitors();setInterval(()=>get("mbdNow").textContent=new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}),1000);
 const cameraPreview=id=>document.querySelector(`[data-preview="${id}"]`)?.click();qsa("[data-cam-select]").forEach(b=>b.onclick=()=>cameraPreview(b.dataset.camSelect));qsa(".source").forEach(b=>b.onclick=()=>cameraPreview(b.dataset.source));qsa("[data-action]").forEach(b=>b.onclick=()=>docGet(b.dataset.action)?.click());get("mbdTestStinger").onclick=()=>docGet("testReplayTransition")?.click();
 qsa("[data-speed]").forEach(b=>b.onclick=()=>{qsa("[data-speed]").forEach(x=>x.classList.remove("active"));b.classList.add("active");if(docGet("replaySpeed"))docGet("replaySpeed").value=b.dataset.speed});qsa("[data-replay-sec]").forEach(b=>b.onclick=()=>{const sec=+b.dataset.replaySec,max=+(docGet("replayBufferLength")?.textContent||30)||30,start=Math.max(0,max-sec);if(docGet("replayStart"))docGet("replayStart").value=start;if(docGet("replayEnd"))docGet("replayEnd").value=max;docGet("replayPreview")?.click()});
 function openFull(tab){document.body.classList.add("mobile-full-control");document.querySelector(`[data-v15-tab="${tab}"]`)?.click();window.scrollTo(0,0)}function returnQuick(){document.body.classList.remove("mobile-full-control");window.scrollTo(0,0)}get("mbdReplay").onclick=()=>docGet("replayPreview")?.click()||openFull("replay");get("mbdFullControl").onclick=()=>openFull("production");qsa("[data-open-tab]").forEach(b=>b.onclick=()=>openFull(b.dataset.openTab));back.onclick=returnQuick;
 if(!window.firebase||!window.Switcher)return;
 const db=Switcher.initFirebase(),sportRef=db.ref(`switcher/${game}/sport`),baseballRef=db.ref("gameState");let sport="baseball",ss={},bs={},cards={},clock={running:false,mode:"countup",baseSeconds:0,startedAt:0};const clamp=(n,a=0,b=999)=>Math.max(a,Math.min(b,Number(n)||0)),fmt=s=>{s=Math.max(0,Math.floor(s));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`},clockSec=()=>{let s=+clock.baseSeconds||0;if(clock.running&&clock.startedAt){const e=Math.max(0,(Date.now()-clock.startedAt)/1000);s=clock.mode==="countdown"?s-e:s+e}return Math.max(0,s)};const logo=(el,url)=>{if(!el)return;el.src=url||"";el.style.visibility=url?"visible":"hidden"};
 function render(){const baseball=sport==="baseball",cfg=ss.config||{},sc=ss.score||{};get("mbdCounts").hidden=!baseball;get("mbdBases").hidden=!baseball;if(baseball){const a=bs.away||{},h=bs.home||{};get("mbdAwayName").textContent=a.name||"VISITANTE";get("mbdHomeName").textContent=h.name||"LOCAL";get("mbdAwayScore").textContent=a.score??0;get("mbdHomeScore").textContent=h.score??0;logo(get("mbdAwayLogo"),a.logo||cfg.awayLogo);logo(get("mbdHomeLogo"),h.logo||cfg.homeLogo);get("mbdPeriod").textContent=`${bs.inning||1} ${(bs.inningSide||"").replace("ALTA","▲").replace("BAJA","▼")}`;get("mbdBalls").textContent=bs.balls||0;get("mbdStrikes").textContent=bs.strikes||0;get("mbdOuts").textContent=bs.outs||0;const bases=bs.bases||{};qsa("[data-base]").forEach(b=>b.classList.toggle("active",!!bases[b.dataset.base]))}else{get("mbdAwayName").textContent=cfg.awayName||"VISITANTE";get("mbdHomeName").textContent=cfg.homeName||"LOCAL";get("mbdAwayScore").textContent=sc.awayScore??0;get("mbdHomeScore").textContent=sc.homeScore??0;logo(get("mbdAwayLogo"),cfg.awayLogo);logo(get("mbdHomeLogo"),cfg.homeLogo);get("mbdPeriod").textContent=sc.period??1}const map={awayYellowCards:"mbdAwayYellow",awayRedCards:"mbdAwayRed",homeYellowCards:"mbdHomeYellow",homeRedCards:"mbdHomeRed"};Object.entries(map).forEach(([k,id])=>get(id).textContent=cards[k]||0)}
 sportRef.on("value",s=>{ss=s.val()||{};sport=ss.current||"baseball";render()});sportRef.child("cards").on("value",s=>{cards=s.val()||{};render()});sportRef.child("clockControl").on("value",s=>clock={...clock,...(s.val()||{})});baseballRef.on("value",s=>{bs=s.val()||{};render()});setInterval(()=>get("mbdClock").textContent=fmt(clockSec()),250);
 qsa("[data-score]").forEach(b=>b.onclick=async()=>{const side=b.dataset.score,d=+b.dataset.delta;if(sport==="baseball")await baseballRef.child(`${side}/score`).set(clamp((bs?.[side]?.score||0)+d));else{const key=side==="home"?"homeScore":"awayScore";await sportRef.child(`score/${key}`).set(clamp((ss.score?.[key]||0)+d))}});qsa("[data-count]").forEach(b=>b.onclick=()=>{const k=b.dataset.count,m=k==="balls"?3:2;baseballRef.child(k).set(clamp((bs[k]||0)+(+b.dataset.delta),0,m))});qsa("[data-card]").forEach(b=>b.onclick=()=>sportRef.child(`cards/${b.dataset.card}`).set(clamp((cards[b.dataset.card]||0)+(+b.dataset.delta),0,9)));qsa("[data-base]").forEach(b=>b.onclick=()=>baseballRef.child(`bases/${b.dataset.base}`).set(!bs?.bases?.[b.dataset.base]));get("mbdClearBases").onclick=()=>baseballRef.child("bases").set({first:false,second:false,third:false});const periodDelta=async d=>{if(sport==="baseball")await baseballRef.child("inning").set(clamp((+bs.inning||1)+d,1,99));else await sportRef.child("score/period").set(String(clamp((parseInt(ss.score?.period)||1)+d,1,99)))};get("mbdPeriodMinus").onclick=()=>periodDelta(-1);get("mbdPeriodPlus").onclick=()=>periodDelta(1);get("mbdClockStart").onclick=()=>docGet("sportClockStart")?.click();get("mbdClockPause").onclick=()=>docGet("sportClockPause")?.click();
});})();
